from fastapi import FastAPI, HTTPException, Body
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Dict, Any, List, Optional
import time

from app.db import db_manager
from app.discovery import generate_disruption_map, select_far_band_candidate
from app.retrieval import retrieve_target_knowledge
from app.sme import abstract_target_concept, translate_schema_to_hobby
from app.evaluator import evaluate_serendipity
from app.challenge import generate_challenge
from app.scoring import grade_response
from app.instrumentation import active_metrics, log_metrics_to_db_and_csv
from app.manual_eval_ui import manual_eval_router

app = FastAPI(
    title="Zero-Shot Cognitive Cross-Pollination Recommender API",
    description="A Structure-Mapping Theory based recommender engine",
    version="1.0.0"
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://zeroshot-cognitive-cross-pollinatio-sooty.vercel.app"
    ],
    allow_origin_regex=r"https://.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(manual_eval_router)

# Pydantic schemas
class ProfileRequest(BaseModel):
    user_id: str
    known_topic: str

class GenerateRequest(BaseModel):
    user_id: str
    known_topic: str
    prompt_variant: Optional[str] = "original"
    distance_band: Optional[str] = "far"

class SubmitRequest(BaseModel):
    user_id: str
    challenge: Dict[str, Any]
    user_answer: str

@app.get("/api/health")
def health_check():
    return {"status": "healthy", "timestamp": time.time()}

@app.get("/api/user/{user_id}")
def get_user_profile(user_id: str):
    """Retrieves user profile: mastery, streak, XP, and history."""
    state = db_manager.get_user_state(user_id)
    return {
        "user_id": user_id,
        "mastery": state.get("mastery", 1.0),
        "streak": state.get("streak", 0),
        "xp": state.get("xp", 0),
        "last_active": state.get("last_active")
    }

@app.post("/api/generate")
def generate_cross_pollination(req: GenerateRequest):
    """
    E2E Pipeline:
    1. Discovery Layer (Disruption map generation & target candidate selection)
    2. Knowledge Retrieval Layer
    3. SME Engine (Abstractor & Translator)
    4. Serendipity Evaluator (with fallback/retry logic)
    5. Micro-challenge Generator
    """
    total_start = time.time()
    user_id = req.user_id
    known_topic = req.known_topic.strip()

    if not known_topic:
        raise HTTPException(status_code=400, detail="Known topic cannot be empty.")

    metrics = {
        "hobby": known_topic,
        "prompt_variant": req.prompt_variant or "original",
        "cache_hit_count": 0,
        "cache_miss_count": 0,
        "groq_latency": 0.0,
        "estimated_token_usage": 0,
        "prompt_template_used": "",
    }
    token = active_metrics.set(metrics)
    try:
        # Get current user mastery
        user_state = db_manager.get_user_state(user_id)
        mastery = user_state.get("mastery", 1.0)

        # 1. Discovery Layer
        try:
            discovery_map = generate_disruption_map(known_topic)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Layer 1 Discovery failed: {str(e)}")

        band_name = req.distance_band or "far"
        if band_name not in ["near", "mid", "far"]:
            band_name = "far"

        if band_name == "far":
            far_candidates = discovery_map.get("far_band", [])
        else:
            raw_names = discovery_map.get(f"{band_name}_band", [])
            far_candidates = []
            for name in raw_names:
                from app.embeddings import get_similarity
                similarity = get_similarity(known_topic, name)
                far_candidates.append({
                    "concept": name,
                    "branch_from": "General concept",
                    "distance_heuristic": f"Selected from {band_name} band",
                    "analogy_potential": "Structural alignment mapping check",
                    "retained_rules": ["System operates logically"],
                    "measured_similarity": round(similarity, 4)
                })

        if not far_candidates:
            raise HTTPException(status_code=500, detail=f"No {band_name}-band concepts generated by the disrupter.")

        # Sort candidates by suitability
        # Select candidate according to user mastery
        if len(far_candidates) > 1:
            if mastery > 2.0:
                far_candidates.sort(key=lambda x: x.get("measured_similarity", 0.5))
            else:
                far_candidates.sort(key=lambda x: x.get("measured_similarity", 0.5), reverse=True)

        # Attempt to process candidates with retry loop on serendipity threshold
        selected_candidate = None
        target_text = ""
        schema = {}
        translation = {}
        eval_result = {}
        
        # Try top 3 candidates
        max_candidates_to_try = min(3, len(far_candidates))
        for i in range(max_candidates_to_try):
            cand = far_candidates[i]
            concept_name = cand["concept"]
            
            # 2. Retrieval Layer
            text = retrieve_target_knowledge(concept_name)
            
            # 3. SME Engine
            extracted_schema = abstract_target_concept(concept_name, text)
            translated_explanation = translate_schema_to_hobby(known_topic, concept_name, extracted_schema)
            
            # 4. Serendipity Evaluator
            evaluation = evaluate_serendipity(known_topic, concept_name, extracted_schema, translated_explanation)
            
            # If valid or it's our last attempt, we proceed with it
            if evaluation.get("is_valid", False) or i == (max_candidates_to_try - 1):
                selected_candidate = cand
                target_text = text
                schema = extracted_schema
                translation = translated_explanation
                eval_result = evaluation
                break

        if not selected_candidate:
            raise HTTPException(status_code=500, detail="Failed to find a viable analogical mapping.")

        # 5. Challenge Generator
        try:
            challenge = generate_challenge(known_topic, selected_candidate["concept"], schema)
        except Exception as e:
            print(f"Layer 5 Challenge generation failed: {e}")
            challenge = {
                "scenario": f"Apply {selected_candidate['concept']} rules to {known_topic}.",
                "question": "How do you share resources dynamically to optimize systems?",
                "required_rule_to_apply": "Dynamic resource trade to support low-performing nodes.",
                "hint": "Check the explanation card for tips."
            }

        # Prepare "How We Got Here" reasoning log for the Gen Z UI transparency
        reasoning_log = {
            "near_band": discovery_map.get("near_band", []),
            "mid_band": discovery_map.get("mid_band", []),
            "selected_concept": selected_candidate["concept"],
            "branched_from": selected_candidate.get("branch_from", "General concept"),
            "distance_heuristic": selected_candidate.get("distance_heuristic", ""),
            "analogy_potential": selected_candidate.get("analogy_potential", ""),
            "measured_similarity": selected_candidate.get("measured_similarity", 0.0),
            "serendipity_evaluation": eval_result
        }

        response_data = {
            "target_topic": selected_candidate["concept"],
            "suggested_title": translation.get("suggested_title", f"{known_topic} meets {selected_candidate['concept']}"),
            "explanation": translation.get("explanation", ""),
            "vocabulary_mapping": translation.get("vocabulary_mapping", {}),
            "challenge": challenge,
            "reasoning_log": reasoning_log,
            "user_state": {
                "mastery": mastery,
                "streak": user_state.get("streak", 0),
                "xp": user_state.get("xp", 0)
            }
        }
        
        # Log telemetry metrics
        duration = time.time() - total_start
        metrics["total_pipeline_time"] = round(duration, 4)
        metrics["api_response_time"] = round(duration, 4)
        metrics["discovered_topic"] = selected_candidate["concept"]
        metrics["challenge_difficulty"] = mastery
        log_metrics_to_db_and_csv(metrics)
        
        return response_data
    finally:
        active_metrics.reset(token)

@app.post("/api/submit-challenge")
def submit_challenge_answer(req: SubmitRequest):
    """
    Layer 6: Rubric Grading & Active Learning Loop
    Takes challenge details and answer, grades it, updates profile state.
    """
    total_start = time.time()
    user_id = req.user_id
    challenge = req.challenge
    user_answer = req.user_answer.strip()

    if not user_answer:
        raise HTTPException(status_code=400, detail="Your response cannot be empty.")

    metrics = {
        "hobby": challenge.get("hobby", "Unknown Hobby"),
        "discovered_topic": challenge.get("target_topic", "Unknown Target"),
        "prompt_variant": challenge.get("prompt_variant", "original"),
        "cache_hit_count": 0,
        "cache_miss_count": 0,
        "groq_latency": 0.0,
        "estimated_token_usage": 0,
        "prompt_template_used": "",
    }
    token = active_metrics.set(metrics)
    try:
        # Grade response and update DB
        try:
            result = grade_response(user_id, challenge, user_answer)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Layer 6 Rubric grading failed: {str(e)}")

        # Log user history
        db_manager.save_history(
            user_id=user_id,
            known_topic=challenge.get("hobby", "Unknown Hobby"), # fallback
            target_topic=challenge.get("target_topic", "Unknown Target"),
            similarity=0.0, # default placeholder
            explanation="",
            challenge=challenge.get("scenario", "") + " | " + challenge.get("question", ""),
            answer=user_answer,
            score=float(result.get("total_score", 0)),
            evaluation=result.get("feedback", ""),
        )

        duration = time.time() - total_start
        metrics["total_pipeline_time"] = round(duration, 4)
        metrics["api_response_time"] = round(duration, 4)
        log_metrics_to_db_and_csv(metrics)

        return result
    finally:
        active_metrics.reset(token)
